export type Country = (typeof countries)[number];

const normalizeCountryName = (inputString: string) => {
	const mappings: Record<string, string> = {
		ã: "a",
		é: "e",
		í: "i",
		ô: "o",
	};

	// Iterate over each character in the input string
	return Array.from(inputString.toLowerCase())
		.map((char) => {
			// Replace the character if it exists in the mappings object
			return mappings[char] || char;
		})
		.join("")
		.replace(/[-' ]/g, "");
};

export const validateGuess = (guess: string) => {
	const guessedCountry = countries.find((country) => {
		return country.matches.find((match) => {
			return normalizeCountryName(match) === normalizeCountryName(guess);
		});
	});

	return guessedCountry;
};

export const countries = [
	{
		id: "AFG",
		name: "Afghanistan",
		iso: "AFG",
		matches: ["Afghanistan", "AF", "Afġānistān"],
	},
	{
		id: "ALB",
		name: "Albania",
		iso: "ALB",
		matches: ["Albania", "AL", "Shqipëri", "Shqipëria", "Shqipnia"],
	},
	{
		id: "DZA",
		name: "Algeria",
		iso: "DZA",
		matches: ["Algeria", "DZ", "Dzayer", "Algérie"],
	},
	{
		id: "AND",
		name: "Andorra",
		iso: "AND",
		matches: [
			"Andorra",
			"AD",
			"Principality of Andorra",
			"Principat d'Andorra",
		],
	},
	{
		id: "AGO",
		name: "Angola",
		iso: "AGO",
		matches: ["Angola", "AO", "República de Angola", "ʁɛpublika de an'ɡɔla"],
	},
	{
		id: "ATG",
		name: "Antigua and Barbuda",
		iso: "ATG",
		matches: ["Antigua and Barbuda", "Antigua", "Barbuda", "AG"],
	},
	{
		id: "ARG",
		name: "Argentina",
		iso: "ARG",
		matches: ["Argentina", "AR", "Argentine Republic", "República Argentina"],
	},
	{
		id: "ARM",
		name: "Armenia",
		iso: "ARM",
		matches: [
			"Armenia",
			"AM",
			"Hayastan",
			"Republic of Armenia",
			"Հայաստանի Հանրապետություն",
		],
	},
	{
		id: "AUS",
		name: "Australia",
		iso: "AUS",
		matches: ["Australia", "AU"],
	},
	{
		id: "AUT",
		name: "Austria",
		iso: "AUT",
		matches: ["Austria", "AT", "Osterreich", "Oesterreich"],
	},
	{
		id: "AZE",
		name: "Azerbaijan",
		iso: "AZE",
		matches: [
			"Azerbaijan",
			"AZ",
			"Republic of Azerbaijan",
			"Azərbaycan Respublikası",
		],
	},
	{
		id: "BHS",
		name: "Bahamas",
		iso: "BHS",
		matches: ["Bahamas", "BS", "Commonwealth of the Bahamas"],
	},
	{
		id: "BHR",
		name: "Bahrain",
		iso: "BHR",
		matches: ["Bahrain", "BH", "Kingdom of Bahrain", "Mamlakat al-Baḥrayn"],
	},
	{
		id: "BGD",
		name: "Bangladesh",
		iso: "BGD",
		matches: [
			"Bangladesh",
			"BD",
			"People's Republic of Bangladesh",
			"Gônôprôjatôntri Bangladesh",
		],
	},
	{
		id: "BRB",
		name: "Barbados",
		iso: "BRB",
		matches: ["Barbados", "BB"],
	},
	{
		id: "BLR",
		name: "Belarus",
		iso: "BLR",
		matches: [
			"Belarus",
			"BY",
			"Bielaruś",
			"Republic of Belarus",
			"Белоруссия",
			"Республика Белоруссия",
		],
	},
	{
		id: "BEL",
		name: "Belgium",
		iso: "BEL",
		matches: [
			"Belgium",
			"BE",
			"België",
			"Belgie",
			"Belgien",
			"Belgique",
			"Kingdom of Belgium",
			"Koninkrijk België",
			"Royaume de Belgique",
			"Königreich Belgien",
		],
	},
	{
		id: "BLZ",
		name: "Belize",
		iso: "BLZ",
		matches: ["Belize", "BZ"],
	},
	{
		id: "BEN",
		name: "Benin",
		iso: "BEN",
		matches: ["Benin", "BJ", "Republic of Benin", "République du Bénin"],
	},
	{
		id: "BTN",
		name: "Bhutan",
		iso: "BTN",
		matches: ["Bhutan", "BT", "Kingdom of Bhutan"],
	},
	{
		id: "BOL",
		name: "Bolivia",
		iso: "BOL",
		matches: [
			"Bolivia",
			"BO",
			"Buliwya",
			"Wuliwya",
			"Bolivia, Plurinational State of",
			"Plurinational State of Bolivia",
			"Estado Plurinacional de Bolivia",
			"Buliwya Mamallaqta",
			"Wuliwya Suyu",
			"Tetã Volívia",
		],
	},
	{
		id: "BIH",
		name: "Bosnia and Herzegovina",
		iso: "BIH",
		matches: [
			"Bosnia and Herzegovina",
			"BA",
			"Bosnia-Herzegovina",
			"Босна и Херцеговина",
		],
	},
	{
		id: "BWA",
		name: "Botswana",
		iso: "BWA",
		matches: ["Botswana", "BW", "Republic of Botswana", "Lefatshe la Botswana"],
	},
	{
		id: "BRA",
		name: "Brazil",
		iso: "BRA",
		matches: [
			"Brazil",
			"BR",
			"Brasil",
			"Federative Republic of Brazil",
			"República Federativa do Brasil",
		],
	},
	{
		id: "BRN",
		name: "Brunei",
		iso: "BRN",
		matches: [
			"Brunei",
			"BN",
			"Brunei Darussalam",
			"Nation of Brunei",
			"the Abode of Peace",
		],
	},
	{
		id: "BGR",
		name: "Bulgaria",
		iso: "BGR",
		matches: ["Bulgaria", "BG", "Republic of Bulgaria", "Република България"],
	},
	{
		id: "BFA",
		name: "Burkina Faso",
		iso: "BFA",
		matches: ["Burkina Faso", "BF"],
	},
	{
		id: "BDI",
		name: "Burundi",
		iso: "BDI",
		matches: [
			"Burundi",
			"BI",
			"Republic of Burundi",
			"Republika y'Uburundi",
			"République du Burundi",
		],
	},
	{
		id: "KHM",
		name: "Cambodia",
		iso: "KHM",
		matches: ["Cambodia", "KH", "Kingdom of Cambodia"],
	},
	{
		id: "CMR",
		name: "Cameroon",
		iso: "CMR",
		matches: [
			"Cameroon",
			"CM",
			"Republic of Cameroon",
			"République du Cameroun",
		],
	},
	{
		id: "CAN",
		name: "Canada",
		iso: "CAN",
		matches: ["Canada", "CA"],
	},
	{
		id: "CPV",
		name: "Cape Verde",
		iso: "CPV",
		matches: [
			"Cape Verde",
			"Cabo Verde",
			"CV",
			"Republic of Cabo Verde",
			"República de Cabo Verde",
		],
	},
	{
		id: "CAF",
		name: "Central African Republic",
		iso: "CAF",
		matches: ["Central African Republic", "CF", "République centrafricaine"],
	},
	{
		id: "TCD",
		name: "Chad",
		iso: "TCD",
		matches: ["Chad", "TD", "Tchad", "Republic of Chad", "République du Tchad"],
	},
	{
		id: "CHL",
		name: "Chile",
		iso: "CHL",
		matches: ["Chile", "CL", "Republic of Chile", "República de Chile"],
	},
	{
		id: "CHN",
		name: "China",
		iso: "CHN",
		matches: [
			"China",
			"CN",
			"Zhōngguó",
			"Zhongguo",
			"Zhonghua",
			"People's Republic of China",
			"中华人民共和国",
			"Zhōnghuá Rénmín Gònghéguó",
		],
	},
	{
		id: "COL",
		name: "Colombia",
		iso: "COL",
		matches: [
			"Colombia",
			"CO",
			"Republic of Colombia",
			"República de Colombia",
		],
	},
	{
		id: "COM",
		name: "Comoros",
		iso: "COM",
		matches: [
			"Comoros",
			"KM",
			"Union of the Comoros",
			"Union des Comores",
			"Udzima wa Komori",
			"al-Ittiḥād al-Qumurī",
		],
	},
	{
		id: "COG",
		name: "Congo",
		iso: "COG",
		matches: ["Congo", "CG", "Congo-Brazzaville"],
	},
	{
		id: "CRI",
		name: "Costa Rica",
		iso: "CRI",
		matches: [
			"Costa Rica",
			"CR",
			"Republic of Costa Rica",
			"República de Costa Rica",
		],
	},
	{
		id: "CIV",
		name: "Côte d'Ivoire",
		iso: "CIV",
		matches: [
			"Ivory Coast",
			"CI",
			"Côte d'Ivoire",
			"Cote d'Ivoire",
			"Republic of Côte d'Ivoire",
			"République de Côte d'Ivoire",
		],
	},
	{
		id: "HRV",
		name: "Croatia",
		iso: "HRV",
		matches: [
			"Croatia",
			"HR",
			"Hrvatska",
			"Republic of Croatia",
			"Republika Hrvatska",
		],
	},
	{
		id: "CUB",
		name: "Cuba",
		iso: "CUB",
		matches: ["Cuba", "CU", "Republic of Cuba", "República de Cuba"],
	},
	{
		id: "CYP",
		name: "Cyprus",
		iso: "CYP",
		matches: [
			"Cyprus",
			"CY",
			"Kýpros",
			"Kıbrıs",
			"Republic of Cyprus",
			"Κυπριακή Δημοκρατία",
			"Kıbrıs Cumhuriyeti",
		],
	},
	{
		id: "CZE",
		name: "Czech Republic",
		iso: "CZE",
		matches: ["Czechia", "CZ", "Česká republika", "Česko"],
	},
	{
		id: "COD",
		name: "Democratic Republic of the Congo",
		iso: "COD",
		matches: [
			"Democratic Republic of the Congo",
			"Democratic Republic of Congo",
		],
	},
	{
		id: "DNK",
		name: "Denmark",
		iso: "DNK",
		matches: [
			"Denmark",
			"DK",
			"Danmark",
			"Kingdom of Denmark",
			"Kongeriget Danmark",
		],
	},
	{
		id: "DJI",
		name: "Djibouti",
		iso: "DJI",
		matches: [
			"Djibouti",
			"DJ",
			"Jabuuti",
			"Gabuuti",
			"Republic of Djibouti",
			"République de Djibouti",
			"Gabuutih Ummuuno",
			"Jamhuuriyadda Jabuuti",
		],
	},
	{
		id: "DMA",
		name: "Dominica",
		iso: "DMA",
		matches: [
			"Dominica",
			"DM",
			"Dominique",
			"Wai‘tu kubuli",
			"Commonwealth of Dominica",
		],
	},
	{
		id: "DOM",
		name: "Dominican Republic",
		iso: "DOM",
		matches: ["Dominican Republic", "Dominican", "DO"],
	},
	{
		id: "ECU",
		name: "Ecuador",
		iso: "ECU",
		matches: ["Ecuador", "EC", "Republic of Ecuador", "República del Ecuador"],
	},
	{
		id: "EGY",
		name: "Egypt",
		iso: "EGY",
		matches: ["Egypt", "EG", "Arab Republic of Egypt"],
	},
	{
		id: "SLV",
		name: "El Salvador",
		iso: "SLV",
		matches: [
			"El Salvador",
			"SV",
			"Republic of El Salvador",
			"República de El Salvador",
		],
	},
	{
		id: "GNQ",
		name: "Equatorial Guinea",
		iso: "GNQ",
		matches: [
			"Equatorial Guinea",
			"GQ",
			"Republic of Equatorial Guinea",
			"República de Guinea Ecuatorial",
			"République de Guinée équatoriale",
			"República da Guiné Equatorial",
		],
	},
	{
		id: "ERI",
		name: "Eritrea",
		iso: "ERI",
		matches: [
			"Eritrea",
			"ER",
			"State of Eritrea",
			"ሃገረ ኤርትራ",
			"Dawlat Iritriyá",
			"ʾErtrā",
			"Iritriyā",
		],
	},
	{
		id: "EST",
		name: "Estonia",
		iso: "EST",
		matches: [
			"Estonia",
			"EE",
			"Eesti",
			"Republic of Estonia",
			"Eesti Vabariik",
		],
	},
	{
		id: "SWZ",
		name: "Eswatini",
		iso: "SWZ",
		matches: [
			"Eswatini",
			"SZ",
			"Swaziland",
			"weSwatini",
			"Swatini",
			"Ngwane",
			"Kingdom of Eswatini",
			"Umbuso weSwatini",
		],
	},
	{
		id: "ETH",
		name: "Ethiopia",
		iso: "ETH",
		matches: [
			"Ethiopia",
			"ET",
			"ʾĪtyōṗṗyā",
			"Federal Democratic Republic of Ethiopia",
			"የኢትዮጵያ ፌዴራላዊ ዲሞክራሲያዊ ሪፐብሊክ",
		],
	},
	{
		id: "FJI",
		name: "Fiji",
		iso: "FJI",
		matches: [
			"Fiji",
			"FJ",
			"Viti",
			"Republic of Fiji",
			"Matanitu ko Viti",
			"Fijī Gaṇarājya",
		],
	},
	{
		id: "FIN",
		name: "Finland",
		iso: "FIN",
		matches: [
			"Finland",
			"FI",
			"Suomi",
			"Republic of Finland",
			"Suomen tasavalta",
			"Republiken Finland",
		],
	},
	{
		id: "FRA",
		name: "France",
		iso: "FRA",
		matches: ["France", "FR", "French Republic", "République française"],
	},
	{
		id: "GAB",
		name: "Gabon",
		iso: "GAB",
		matches: ["Gabon", "GA", "Gabonese Republic", "République Gabonaise"],
	},
	{
		id: "GMB",
		name: "Gambia",
		iso: "GMB",
		matches: ["Gambia", "GM", "Republic of the Gambia"],
	},
	{
		id: "GEO",
		name: "Georgia",
		iso: "GEO",
		matches: ["Georgia", "GE", "Sakartvelo"],
	},
	{
		id: "DEU",
		name: "Germany",
		iso: "DEU",
		matches: [
			"Germany",
			"DE",
			"Federal Republic of Germany",
			"Bundesrepublik Deutschland",
		],
	},
	{
		id: "GHA",
		name: "Ghana",
		iso: "GHA",
		matches: ["Ghana", "GH"],
	},
	{
		id: "GRC",
		name: "Greece",
		iso: "GRC",
		matches: [
			"Greece",
			"GR",
			"Elláda",
			"Hellenic Republic",
			"Ελληνική Δημοκρατία",
		],
	},
	{
		id: "GRD",
		name: "Grenada",
		iso: "GRD",
		matches: ["Grenada", "GD"],
	},
	{
		id: "GTM",
		name: "Guatemala",
		iso: "GTM",
		matches: ["Guatemala", "GT"],
	},
	{
		id: "GIN",
		name: "Guinea",
		iso: "GIN",
		matches: ["Guinea", "GN", "Republic of Guinea", "République de Guinée"],
	},
	{
		id: "GNB",
		name: "Guinea-Bissau",
		iso: "GNB",
		matches: [
			"Guinea-Bissau",
			"GW",
			"Republic of Guinea-Bissau",
			"República da Guiné-Bissau",
		],
	},
	{
		id: "GUY",
		name: "Guyana",
		iso: "GUY",
		matches: ["Guyana", "GY", "Co-operative Republic of Guyana"],
	},
	{
		id: "HTI",
		name: "Haiti",
		iso: "HTI",
		matches: [
			"Haiti",
			"HT",
			"Republic of Haiti",
			"République d'Haïti",
			"Repiblik Ayiti",
		],
	},
	{
		id: "HND",
		name: "Honduras",
		iso: "HND",
		matches: [
			"Honduras",
			"HN",
			"Republic of Honduras",
			"República de Honduras",
		],
	},
	{
		id: "HUN",
		name: "Hungary",
		iso: "HUN",
		matches: ["Hungary", "HU"],
	},
	{
		id: "ISL",
		name: "Iceland",
		iso: "ISL",
		matches: [
			"Iceland",
			"IS",
			"Island",
			"Republic of Iceland",
			"Lýðveldið Ísland",
		],
	},
	{
		id: "IND",
		name: "India",
		iso: "IND",
		matches: [
			"India",
			"IN",
			"Bhārat",
			"Republic of India",
			"Bharat Ganrajya",
			"இநதய",
		],
	},
	{
		id: "IDN",
		name: "Indonesia",
		iso: "IDN",
		matches: ["Indonesia", "ID", "Republic of Indonesia", "Republik Indonesia"],
	},
	{
		id: "IRN",
		name: "Iran",
		iso: "IRN",
		matches: [
			"Iran",
			"IR",
			"Islamic Republic of Iran",
			"Iran, Islamic Republic of",
			"Jomhuri-ye Eslāmi-ye Irān",
		],
	},
	{
		id: "IRQ",
		name: "Iraq",
		iso: "IRQ",
		matches: ["Iraq", "IQ", "Republic of Iraq", "Jumhūriyyat al-‘Irāq"],
	},
	{
		id: "IRL",
		name: "Ireland",
		iso: "IRL",
		matches: [
			"Ireland",
			"IE",
			"Éire",
			"Republic of Ireland",
			"Poblacht na hÉireann",
		],
	},
	{
		id: "ISR",
		name: "Israel",
		iso: "ISR",
		matches: [
			"Israel",
			"IL",
			"State of Israel",
			"Medīnat Yisrā'el",
			"Palestine",
		],
	},
	{
		id: "ITA",
		name: "Italy",
		iso: "ITA",
		matches: ["Italy", "IT", "Italian Republic", "Repubblica italiana"],
	},
	{
		id: "JAM",
		name: "Jamaica",
		iso: "JAM",
		matches: ["Jamaica", "JM"],
	},
	{
		id: "JPN",
		name: "Japan",
		iso: "JPN",
		matches: ["Japan", "JP", "Nippon", "Nihon"],
	},
	{
		id: "JOR",
		name: "Jordan",
		iso: "JOR",
		matches: [
			"Jordan",
			"JO",
			"Hashemite Kingdom of Jordan",
			"al-Mamlakah al-Urdunīyah al-Hāshimīyah",
		],
	},
	{
		id: "KAZ",
		name: "Kazakhstan",
		iso: "KAZ",
		matches: [
			"Kazakhstan",
			"KZ",
			"Qazaqstan",
			"Казахстан",
			"Republic of Kazakhstan",
			"Қазақстан Республикасы",
			"Qazaqstan Respublïkası",
			"Республика Казахстан",
			"Respublika Kazakhstan",
		],
	},
	{
		id: "KEN",
		name: "Kenya",
		iso: "KEN",
		matches: ["Kenya", "KE", "Republic of Kenya", "Jamhuri ya Kenya"],
	},
	{
		id: "KIR",
		name: "Kiribati",
		iso: "KIR",
		matches: ["Kiribati", "KI", "Republic of Kiribati", "Ribaberiki Kiribati"],
	},
	{
		id: "KOS",
		name: "Kosovo",
		iso: "KOS",
		matches: ["Kosovo"],
	},
	{
		id: "KWT",
		name: "Kuwait",
		iso: "KWT",
		matches: ["Kuwait", "KW", "State of Kuwait", "Dawlat al-Kuwait"],
	},
	{
		id: "KGZ",
		name: "Kyrgyzstan",
		iso: "KGZ",
		matches: [
			"Kyrgyzstan",
			"KG",
			"Киргизия",
			"Kyrgyz Republic",
			"Кыргыз Республикасы",
			"Kyrgyz Respublikasy",
		],
	},
	{
		id: "LAO",
		name: "Laos",
		iso: "LAO",
		matches: [
			"Laos",
			"LA",
			"Lao",
			"Lao People's Democratic Republic",
			"Sathalanalat Paxathipatai Paxaxon Lao",
		],
	},
	{
		id: "LVA",
		name: "Latvia",
		iso: "LVA",
		matches: ["Latvia", "LV", "Republic of Latvia", "Latvijas Republika"],
	},
	{
		id: "LBN",
		name: "Lebanon",
		iso: "LBN",
		matches: [
			"Lebanon",
			"LB",
			"Lebanese Republic",
			"Al-Jumhūrīyah Al-Libnānīyah",
		],
	},
	{
		id: "LSO",
		name: "Lesotho",
		iso: "LSO",
		matches: ["Lesotho", "LS", "Kingdom of Lesotho", "Muso oa Lesotho"],
	},
	{
		id: "LBR",
		name: "Liberia",
		iso: "LBR",
		matches: ["Liberia", "LR", "Republic of Liberia"],
	},
	{
		id: "LBY",
		name: "Libya",
		iso: "LBY",
		matches: ["Libya", "LY", "State of Libya", "Dawlat Libya"],
	},
	{
		id: "LIE",
		name: "Liechtenstein",
		iso: "LIE",
		matches: [
			"Liechtenstein",
			"LI",
			"Principality of Liechtenstein",
			"Fürstentum Liechtenstein",
		],
	},
	{
		id: "LTU",
		name: "Lithuania",
		iso: "LTU",
		matches: [
			"Lithuania",
			"LT",
			"Republic of Lithuania",
			"Lietuvos Respublika",
		],
	},
	{
		id: "LUX",
		name: "Luxembourg",
		iso: "LUX",
		matches: [
			"Luxembourg",
			"LU",
			"Grand Duchy of Luxembourg",
			"Grand-Duché de Luxembourg",
			"Großherzogtum Luxemburg",
			"Groussherzogtum Lëtzebuerg",
		],
	},
	{
		id: "MDG",
		name: "Madagascar",
		iso: "MDG",
		matches: [
			"Madagascar",
			"MG",
			"Republic of Madagascar",
			"Repoblikan'i Madagasikara",
			"République de Madagascar",
		],
	},
	{
		id: "MWI",
		name: "Malawi",
		iso: "MWI",
		matches: ["Malawi", "MW", "Republic of Malawi"],
	},
	{
		id: "MYS",
		name: "Malaysia",
		iso: "MYS",
		matches: ["Malaysia", "MY"],
	},
	{
		id: "MDV",
		name: "Maldives",
		iso: "MDV",
		matches: [
			"Maldives",
			"MV",
			"Maldive Islands",
			"Republic of the Maldives",
			"Dhivehi Raajjeyge Jumhooriyya",
		],
	},
	{
		id: "MLI",
		name: "Mali",
		iso: "MLI",
		matches: ["Mali", "ML", "Republic of Mali", "République du Mali"],
	},
	{
		id: "MLT",
		name: "Malta",
		iso: "MLT",
		matches: ["Malta", "MT", "Republic of Malta", "Repubblika ta' Malta"],
	},
	{
		id: "MHL",
		name: "Marshall Islands",
		iso: "MHL",
		matches: [
			"Marshall Islands",
			"MH",
			"Republic of the Marshall Islands",
			"Aolepān Aorōkin Majeļ",
		],
	},
	{
		id: "MRT",
		name: "Mauritania",
		iso: "MRT",
		matches: [
			"Mauritania",
			"MR",
			"Islamic Republic of Mauritania",
			"al-Jumhūriyyah al-ʾIslāmiyyah al-Mūrītāniyyah",
		],
	},
	{
		id: "MUS",
		name: "Mauritius",
		iso: "MUS",
		matches: [
			"Mauritius",
			"MU",
			"Republic of Mauritius",
			"République de Maurice",
		],
	},
	{
		id: "MEX",
		name: "Mexico",
		iso: "MEX",
		matches: [
			"Mexico",
			"MX",
			"Mexicanos",
			"United Mexican States",
			"Estados Unidos Mexicanos",
		],
	},
	{
		id: "FSM",
		name: "Micronesia",
		iso: "FSM",
		matches: [
			"Micronesia",
			"FM",
			"Federated States of Micronesia",
			"Micronesia, Federated States of",
		],
	},
	{
		id: "MDA",
		name: "Moldova",
		iso: "MDA",
		matches: [
			"Moldova",
			"MD",
			"Moldova, Republic of",
			"Republic of Moldova",
			"Republica Moldova",
		],
	},
	{
		id: "MCO",
		name: "Monaco",
		iso: "MCO",
		matches: [
			"Monaco",
			"MC",
			"Principality of Monaco",
			"Principauté de Monaco",
		],
	},
	{
		id: "MNG",
		name: "Mongolia",
		iso: "MNG",
		matches: ["Mongolia", "MN"],
	},
	{
		id: "MNE",
		name: "Montenegro",
		iso: "MNE",
		matches: ["Montenegro", "ME", "Crna Gora"],
	},
	{
		id: "MAR",
		name: "Morocco",
		iso: "MAR",
		matches: [
			"Morocco",
			"MA",
			"Kingdom of Morocco",
			"Al-Mamlakah al-Maġribiyah",
		],
	},
	{
		id: "MOZ",
		name: "Mozambique",
		iso: "MOZ",
		matches: [
			"Mozambique",
			"MZ",
			"Republic of Mozambique",
			"República de Moçambique",
		],
	},
	{
		id: "MMR",
		name: "Myanmar",
		iso: "MMR",
		matches: [
			"Myanmar",
			"MM",
			"Burma",
			"Republic of the Union of Myanmar",
			"Pyidaunzu Thanmăda Myăma Nainngandaw",
		],
	},
	{
		id: "NAM",
		name: "Namibia",
		iso: "NAM",
		matches: ["Namibia", "NA", "Namibië", "Republic of Namibia"],
	},
	{
		id: "NRU",
		name: "Nauru",
		iso: "NRU",
		matches: [
			"Nauru",
			"NR",
			"Naoero",
			"Pleasant Island",
			"Republic of Nauru",
			"Ripublik Naoero",
		],
	},
	{
		id: "NPL",
		name: "Nepal",
		iso: "NPL",
		matches: [
			"Nepal",
			"NP",
			"Federal Democratic Republic of Nepal",
			"Loktāntrik Ganatantra Nepāl",
		],
	},
	{
		id: "NLD",
		name: "Netherlands",
		iso: "NLD",
		matches: ["Netherlands", "NL", "Holland", "Nederland", "The Netherlands"],
	},
	{
		id: "NZL",
		name: "New Zealand",
		iso: "NZL",
		matches: ["New Zealand", "NZ", "Aotearoa"],
	},
	{
		id: "NIC",
		name: "Nicaragua",
		iso: "NIC",
		matches: [
			"Nicaragua",
			"NI",
			"Republic of Nicaragua",
			"República de Nicaragua",
		],
	},
	{
		id: "NER",
		name: "Niger",
		iso: "NER",
		matches: ["Niger", "NE", "Nijar"],
	},
	{
		id: "NGA",
		name: "Nigeria",
		iso: "NGA",
		matches: [
			"Nigeria",
			"NG",
			"Nijeriya",
			"Naíjíríà",
			"Federal Republic of Nigeria",
		],
	},
	{
		id: "PRK",
		name: "North Korea",
		iso: "PRK",
		matches: [
			"North Korea",
			"KP",
			"Democratic People's Republic of Korea",
			"DPRK",
			"조선민주주의인민공화국",
			"Chosŏn Minjujuŭi Inmin Konghwaguk",
			"Korea, Democratic People's Republic of",
			"북한",
			"북조선",
		],
	},
	{
		id: "MKD",
		name: "North Macedonia",
		iso: "MKD",
		matches: [
			"North Macedonia",
			"MK",
			"The former Yugoslav Republic of Macedonia",
			"Republic of North Macedonia",
			"Macedonia, The Former Yugoslav Republic of",
			"Република Северна Македонија",
			"Macedonia",
		],
	},
	{
		id: "NOR",
		name: "Norway",
		iso: "NOR",
		matches: [
			"Norway",
			"NO",
			"Norge",
			"Noreg",
			"Kingdom of Norway",
			"Kongeriket Norge",
			"Kongeriket Noreg",
		],
	},
	{
		id: "OMN",
		name: "Oman",
		iso: "OMN",
		matches: ["Oman", "OM", "Sultanate of Oman", "Salṭanat ʻUmān"],
	},
	{
		id: "PAK",
		name: "Pakistan",
		iso: "PAK",
		matches: [
			"Pakistan",
			"PK",
			"Pākistān",
			"Islamic Republic of Pakistan",
			"Islāmī Jumhūriya'eh Pākistān",
		],
	},
	{
		id: "PLW",
		name: "Palau",
		iso: "PLW",
		matches: ["Palau", "PW", "Republic of Palau", "Beluu er a Belau"],
	},
	{
		id: "PAN",
		name: "Panama",
		iso: "PAN",
		matches: ["Panama", "PA", "Republic of Panama", "República de Panamá"],
	},
	{
		id: "PNG",
		name: "Papua New Guinea",
		iso: "PNG",
		matches: [
			"Papua New Guinea",
			"PG",
			"Independent State of Papua New Guinea",
			"Independen Stet bilong Papua Niugini",
		],
	},
	{
		id: "PRY",
		name: "Paraguay",
		iso: "PRY",
		matches: [
			"Paraguay",
			"PY",
			"Republic of Paraguay",
			"República del Paraguay",
			"Tetã Paraguái",
		],
	},
	{
		id: "PER",
		name: "Peru",
		iso: "PER",
		matches: ["Peru", "PE", "Republic of Peru", "República del Perú"],
	},
	{
		id: "PHL",
		name: "Philippines",
		iso: "PHL",
		matches: [
			"Philippines",
			"PH",
			"Republic of the Philippines",
			"Repúblika ng Pilipinas",
		],
	},
	{
		id: "POL",
		name: "Poland",
		iso: "POL",
		matches: ["Poland", "PL", "Republic of Poland", "Rzeczpospolita Polska"],
	},
	{
		id: "PRT",
		name: "Portugal",
		iso: "PRT",
		matches: [
			"Portugal",
			"PT",
			"Portuguesa",
			"Portuguese Republic",
			"República Portuguesa",
		],
	},
	{
		id: "QAT",
		name: "Qatar",
		iso: "QAT",
		matches: ["Qatar", "QA", "State of Qatar", "Dawlat Qaṭar"],
	},
	{
		id: "ROU",
		name: "Romania",
		iso: "ROU",
		matches: ["Romania", "RO", "Rumania", "Roumania", "România"],
	},
	{
		id: "RUS",
		name: "Russia",
		iso: "RUS",
		matches: ["Russia", "RU", "Russian Federation", "Российская Федерация"],
	},
	{
		id: "RWA",
		name: "Rwanda",
		iso: "RWA",
		matches: [
			"Rwanda",
			"RW",
			"Republic of Rwanda",
			"Repubulika y'u Rwanda",
			"République du Rwanda",
		],
	},
	{
		id: "KNA",
		name: "Saint Kitts and Nevis",
		iso: "KNA",
		matches: [
			"Saint Kitts and Nevis",
			"Saint Kitts",
			"St Kitts and Nevis",
			"St Kitts",
			"Nevis",
			"KN",
			"Federation of Saint Christopher and Nevis",
		],
	},
	{
		id: "LCA",
		name: "Saint Lucia",
		iso: "LCA",
		matches: ["Saint Lucia", "St Lucia", "LC"],
	},
	{
		id: "VCT",
		name: "Saint Vincent and the Grenadines",
		iso: "VCT",
		matches: [
			"Saint Vincent and the Grenadines",
			"Saint Vincent and Grenadines",
			"Saint Vincent",
			"St Vincent and the Grenadines",
			"St Vincent and Grenadines",
			"St Vincent",
			"Grendadines",
		],
	},
	{
		id: "WSM",
		name: "Samoa",
		iso: "WSM",
		matches: [
			"Samoa",
			"WS",
			"Independent State of Samoa",
			"Malo Saʻoloto Tutoʻatasi o Sāmoa",
		],
	},
	{
		id: "SMR",
		name: "San Marino",
		iso: "SMR",
		matches: [
			"San Marino",
			"SM",
			"Republic of San Marino",
			"Repubblica di San Marino",
		],
	},
	{
		id: "STP",
		name: "São Tomé and Príncipe",
		iso: "STP",
		matches: [
			"São Tomé and Príncipe",
			"ST",
			"Democratic Republic of São Tomé and Príncipe",
			"Sao Tome and Principe",
			"República Democrática de São Tomé e Príncipe",
		],
	},
	{
		id: "SAU",
		name: "Saudi Arabia",
		iso: "SAU",
		matches: [
			"Saudi Arabia",
			"Saudi",
			"SA",
			"Kingdom of Saudi Arabia",
			"Al-Mamlakah al-‘Arabiyyah as-Su‘ūdiyyah",
		],
	},
	{
		id: "SEN",
		name: "Senegal",
		iso: "SEN",
		matches: ["Senegal", "SN", "Republic of Senegal", "République du Sénégal"],
	},
	{
		id: "SRB",
		name: "Serbia",
		iso: "SRB",
		matches: [
			"Serbia",
			"RS",
			"Srbija",
			"Republika Srbija",
			"Србија",
			"Република Србија",
			"Republic of Serbia",
		],
	},
	{
		id: "SYC",
		name: "Seychelles",
		iso: "SYC",
		matches: [
			"Seychelles",
			"SC",
			"Republic of Seychelles",
			"Repiblik Sesel",
			"République des Seychelles",
		],
	},
	{
		id: "SLE",
		name: "Sierra Leone",
		iso: "SLE",
		matches: ["Sierra Leone", "SL", "Republic of Sierra Leone"],
	},
	{
		id: "SGP",
		name: "Singapore",
		iso: "SGP",
		matches: [
			"Singapore",
			"SG",
			"Singapura",
			"Republik Singapura",
			"新加坡共和国",
		],
	},
	{
		id: "SVK",
		name: "Slovakia",
		iso: "SVK",
		matches: ["Slovakia", "SK", "Slovak Republic", "Slovenská republika"],
	},
	{
		id: "SVN",
		name: "Slovenia",
		iso: "SVN",
		matches: ["Slovenia", "SI", "Republic of Slovenia", "Republika Slovenija"],
	},
	{
		id: "SLB",
		name: "Solomon Islands",
		iso: "SLB",
		matches: ["Solomon Islands", "SB"],
	},
	{
		id: "SOM",
		name: "Somalia",
		iso: "SOM",
		matches: [
			"Somalia",
			"SO",
			"aṣ-Ṣūmāl",
			"Federal Republic of Somalia",
			"Jamhuuriyadda Federaalka Soomaaliya",
			"Jumhūriyyat aṣ-Ṣūmāl al-Fiderāliyya",
		],
	},
	{
		id: "ZAF",
		name: "South Africa",
		iso: "ZAF",
		matches: [
			"South Africa",
			"ZA",
			"RSA",
			"Suid-Afrika",
			"Republic of South Africa",
		],
	},
	{
		id: "KOR",
		name: "South Korea",
		iso: "KOR",
		matches: [
			"South Korea",
			"KR",
			"Korea, Republic of",
			"Republic of Korea",
			"남한",
			"남조선",
		],
	},
	{
		id: "SSD",
		name: "South Sudan",
		iso: "SSD",
		matches: ["South Sudan", "SS"],
	},
	{
		id: "ESP",
		name: "Spain",
		iso: "ESP",
		matches: ["Spain", "ES", "Kingdom of Spain", "Reino de España"],
	},
	{
		id: "LKA",
		name: "Sri Lanka",
		iso: "LKA",
		matches: [
			"Sri Lanka",
			"LK",
			"ilaṅkai",
			"Democratic Socialist Republic of Sri Lanka",
		],
	},
	{
		id: "SDN",
		name: "Sudan",
		iso: "SDN",
		matches: ["Sudan", "SD", "Republic of the Sudan", "Jumhūrīyat as-Sūdān"],
	},
	{
		id: "SUR",
		name: "Suriname",
		iso: "SUR",
		matches: [
			"Suriname",
			"SR",
			"Sarnam",
			"Sranangron",
			"Republic of Suriname",
			"Republiek Suriname",
		],
	},
	{
		id: "SWE",
		name: "Sweden",
		iso: "SWE",
		matches: ["Sweden", "SE", "Kingdom of Sweden", "Konungariket Sverige"],
	},
	{
		id: "CHE",
		name: "Switzerland",
		iso: "CHE",
		matches: [
			"Switzerland",
			"CH",
			"Swiss Confederation",
			"Schweiz",
			"Suisse",
			"Svizzera",
			"Svizra",
		],
	},
	{
		id: "SYR",
		name: "Syria",
		iso: "SYR",
		matches: [
			"Syria",
			"SY",
			"Syrian Arab Republic",
			"Al-Jumhūrīyah Al-ʻArabīyah As-Sūrīyah",
		],
	},
	{
		id: "TWN",
		name: "Taiwan",
		iso: "TWN",
		matches: [
			"Taiwan",
			"TW",
			"Táiwān",
			"Republic of China",
			"中華民國",
			"Zhōnghuá Mínguó",
			"Chinese Taipei",
		],
	},
	{
		id: "TJK",
		name: "Tajikistan",
		iso: "TJK",
		matches: [
			"Tajikistan",
			"TJ",
			"Toçikiston",
			"Republic of Tajikistan",
			"Ҷумҳурии Тоҷикистон",
			"Çumhuriyi Toçikiston",
		],
	},
	{
		id: "TZA",
		name: "Tanzania",
		iso: "TZA",
		matches: [
			"Tanzania",
			"TZ",
			"Tanzania, United Republic of",
			"United Republic of Tanzania",
			"Jamhuri ya Muungano wa Tanzania",
		],
	},
	{
		id: "THA",
		name: "Thailand",
		iso: "THA",
		matches: [
			"Thailand",
			"TH",
			"Prathet",
			"Thai",
			"Kingdom of Thailand",
			"ราชอาณาจกรไทย",
			"Ratcha Anachak Thai",
		],
	},
	{
		id: "TLS",
		name: "Timor-Leste",
		iso: "TLS",
		matches: [
			"Timor-Leste",
			"TL",
			"East Timor",
			"Timor",
			"Democratic Republic of Timor-Leste",
			"República Democrática de Timor-Leste",
			"Repúblika Demokrátika Timór-Leste",
			"Timór Lorosa'e",
			"Timor Lorosae",
		],
	},
	{
		id: "TGO",
		name: "Togo",
		iso: "TGO",
		matches: [
			"Togo",
			"TG",
			"Togolese",
			"Togolese Republic",
			"République Togolaise",
		],
	},
	{
		id: "TON",
		name: "Tonga",
		iso: "TON",
		matches: ["Tonga", "TO"],
	},
	{
		id: "TTO",
		name: "Trinidad and Tobago",
		iso: "TTO",
		matches: ["Trinidad and Tobago", "TT", "Republic of Trinidad and Tobago"],
	},
	{
		id: "TUN",
		name: "Tunisia",
		iso: "TUN",
		matches: [
			"Tunisia",
			"TN",
			"Republic of Tunisia",
			"al-Jumhūriyyah at-Tūnisiyyah",
		],
	},
	{
		id: "TUR",
		name: "Turkey",
		iso: "TUR",
		matches: [
			"Turkey",
			"Türkiye",
			"TR",
			"Turkiye",
			"Republic of Turkey",
			"Türkiye Cumhuriyeti",
		],
	},
	{
		id: "TKM",
		name: "Turkmenistan",
		iso: "TKM",
		matches: ["Turkmenistan", "TM"],
	},
	{
		id: "TUV",
		name: "Tuvalu",
		iso: "TUV",
		matches: ["Tuvalu", "TV"],
	},
	{
		id: "UGA",
		name: "Uganda",
		iso: "UGA",
		matches: ["Uganda", "UG", "Republic of Uganda", "Jamhuri ya Uganda"],
	},
	{
		id: "UKR",
		name: "Ukraine",
		iso: "UKR",
		matches: ["Ukraine", "UA", "Ukrayina"],
	},
	{
		id: "ARE",
		name: "United Arab Emirates",
		iso: "ARE",
		matches: ["United Arab Emirates", "AE", "UAE", "Emirates"],
	},
	{
		id: "GBR",
		name: "United Kingdom",
		iso: "GBR",
		matches: ["United Kingdom", "GB", "UK", "Great Britain"],
	},
	{
		id: "USA",
		name: "United States of America",
		iso: "USA",
		matches: ["United States", "US", "USA", "United States of America"],
	},
	{
		id: "URY",
		name: "Uruguay",
		iso: "URY",
		matches: [
			"Uruguay",
			"UY",
			"Oriental Republic of Uruguay",
			"República Oriental del Uruguay",
		],
	},
	{
		id: "UZB",
		name: "Uzbekistan",
		iso: "UZB",
		matches: [
			"Uzbekistan",
			"UZ",
			"Republic of Uzbekistan",
			"O‘zbekiston Respublikasi",
			"Ўзбекистон Республикаси",
		],
	},
	{
		id: "VUT",
		name: "Vanuatu",
		iso: "VUT",
		matches: [
			"Vanuatu",
			"VU",
			"Republic of Vanuatu",
			"Ripablik blong Vanuatu",
			"République de Vanuatu",
		],
	},
	{
		id: "VAT",
		name: "Vatican City",
		iso: "VAT",
		matches: [
			"Vatican City",
			"VA",
			"Holy See (Vatican City State)",
			"Vatican City State",
			"Vatican",
			"Stato della Città del Vaticano",
		],
	},
	{
		id: "VEN",
		name: "Venezuela",
		iso: "VEN",
		matches: [
			"Venezuela",
			"VE",
			"Bolivarian Republic of Venezuela",
			"Venezuela, Bolivarian Republic of",
			"República Bolivariana de Venezuela",
		],
	},
	{
		id: "VNM",
		name: "Vietnam",
		iso: "VNM",
		matches: [
			"Vietnam",
			"VN",
			"Socialist Republic of Vietnam",
			"Cộng hòa Xã hội chủ nghĩa Việt Nam",
			"Viet Nam",
		],
	},
	{
		id: "YEM",
		name: "Yemen",
		iso: "YEM",
		matches: ["Yemen", "YE", "Yemeni Republic", "al-Jumhūriyyah al-Yamaniyyah"],
	},
	{
		id: "ZMB",
		name: "Zambia",
		iso: "ZMB",
		matches: ["Zambia", "ZM", "Republic of Zambia"],
	},
	{
		id: "ZWE",
		name: "Zimbabwe",
		iso: "ZWE",
		matches: ["Zimbabwe", "ZW", "Republic of Zimbabwe"],
	},
];
