// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file v1/messages/game_settings.proto (package core.v1.messages, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/messages/game_settings.proto.
 */
export const file_v1_messages_game_settings: GenFile = /*@__PURE__*/
  fileDesc("Ch92MS9tZXNzYWdlcy9nYW1lX3NldHRpbmdzLnByb3RvEhBjb3JlLnYxLm1lc3NhZ2VzIkQKDEdhbWVTZXR0aW5ncxITCgttYXhfcGxheWVycxgBIAEoBRINCgVkZWxheRgCIAEoBRIQCghkdXJhdGlvbhgDIAEoBWIGcHJvdG8z");

/**
 * @generated from message core.v1.messages.GameSettings
 */
export type GameSettings = Message<"core.v1.messages.GameSettings"> & {
  /**
   * @generated from field: int32 max_players = 1;
   */
  maxPlayers: number;

  /**
   * @generated from field: int32 delay = 2;
   */
  delay: number;

  /**
   * @generated from field: int32 duration = 3;
   */
  duration: number;
};

/**
 * Describes the message core.v1.messages.GameSettings.
 * Use `create(GameSettingsSchema)` to create a new message.
 */
export const GameSettingsSchema: GenMessage<GameSettings> = /*@__PURE__*/
  messageDesc(file_v1_messages_game_settings, 0);

