// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file v1/messages/game_statuses.proto (package core.v1.messages, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/messages/game_statuses.proto.
 */
export const file_v1_messages_game_statuses: GenFile = /*@__PURE__*/
  fileDesc("Ch92MS9tZXNzYWdlcy9nYW1lX3N0YXR1c2VzLnByb3RvEhBjb3JlLnYxLm1lc3NhZ2VzImwKCkdhbWVTdGF0dXMSLgoKc3RhcnRlZF9hdBgBIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKY3JlYXRlZF9hdBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBiBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * @generated from message core.v1.messages.GameStatus
 */
export type GameStatus = Message<"core.v1.messages.GameStatus"> & {
  /**
   * @generated from field: google.protobuf.Timestamp started_at = 1;
   */
  startedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 2;
   */
  createdAt?: Timestamp;
};

/**
 * Describes the message core.v1.messages.GameStatus.
 * Use `create(GameStatusSchema)` to create a new message.
 */
export const GameStatusSchema: GenMessage<GameStatus> = /*@__PURE__*/
  messageDesc(file_v1_messages_game_statuses, 0);

