// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file v1/messages/room_connections.proto (package core.v1.messages, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/messages/room_connections.proto.
 */
export const file_v1_messages_room_connections: GenFile = /*@__PURE__*/
  fileDesc("CiJ2MS9tZXNzYWdlcy9yb29tX2Nvbm5lY3Rpb25zLnByb3RvEhBjb3JlLnYxLm1lc3NhZ2VzIjgKD1Jvb21Db25uZWN0aW9ucxIlCgV1c2VycxgBIAMoCzIWLmNvcmUudjEubWVzc2FnZXMuVXNlciJKCgRVc2VyEgoKAmlkGAEgASgJEhAKCHVzZXJuYW1lGAIgASgJEiQKBHJvbGUYAyABKA4yFi5jb3JlLnYxLm1lc3NhZ2VzLlJvbGUqOwoEUm9sZRIUChBST0xFX1VOU1BFQ0lGSUVEEAASDQoJUk9MRV9IT1NUEAESDgoKUk9MRV9HVUVTVBACYgZwcm90bzM");

/**
 * @generated from message core.v1.messages.RoomConnections
 */
export type RoomConnections = Message<"core.v1.messages.RoomConnections"> & {
  /**
   * @generated from field: repeated core.v1.messages.User users = 1;
   */
  users: User[];
};

/**
 * Describes the message core.v1.messages.RoomConnections.
 * Use `create(RoomConnectionsSchema)` to create a new message.
 */
export const RoomConnectionsSchema: GenMessage<RoomConnections> = /*@__PURE__*/
  messageDesc(file_v1_messages_room_connections, 0);

/**
 * @generated from message core.v1.messages.User
 */
export type User = Message<"core.v1.messages.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: core.v1.messages.Role role = 3;
   */
  role: Role;
};

/**
 * Describes the message core.v1.messages.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_v1_messages_room_connections, 1);

/**
 * @generated from enum core.v1.messages.Role
 */
export enum Role {
  /**
   * @generated from enum value: ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ROLE_HOST = 1;
   */
  HOST = 1,

  /**
   * @generated from enum value: ROLE_GUEST = 2;
   */
  GUEST = 2,
}

/**
 * Describes the enum core.v1.messages.Role.
 */
export const RoleSchema: GenEnum<Role> = /*@__PURE__*/
  enumDesc(file_v1_messages_room_connections, 0);

