// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file v1/messages/user_messages.proto (package core.v1.messages, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file v1/messages/user_messages.proto.
 */
export const file_v1_messages_user_messages: GenFile = /*@__PURE__*/
  fileDesc("Ch92MS9tZXNzYWdlcy91c2VyX21lc3NhZ2VzLnByb3RvEhBjb3JlLnYxLm1lc3NhZ2VzIqEBCgtVc2VyTWVzc2FnZRIPCgd1c2VyX2lkGAEgASgJEg8KB21lc3NhZ2UYAiABKAkSMQoKbWV0YV9ndWVzcxgDIAEoCzIbLmNvcmUudjEubWVzc2FnZXMuTWV0YUd1ZXNzSAASNQoMbWV0YV9tZXNzYWdlGAQgASgLMh0uY29yZS52MS5tZXNzYWdlcy5NZXRhTWVzc2FnZUgAQgYKBG1ldGEiMwoJTWV0YUd1ZXNzEhIKCmlzX2NvcnJlY3QYASABKAgSEgoKY291bnRyeV9pZBgCIAEoCSINCgtNZXRhTWVzc2FnZWIGcHJvdG8z");

/**
 * @generated from message core.v1.messages.UserMessage
 */
export type UserMessage = Message<"core.v1.messages.UserMessage"> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from oneof core.v1.messages.UserMessage.meta
   */
  meta: {
    /**
     * @generated from field: core.v1.messages.MetaGuess meta_guess = 3;
     */
    value: MetaGuess;
    case: "metaGuess";
  } | {
    /**
     * @generated from field: core.v1.messages.MetaMessage meta_message = 4;
     */
    value: MetaMessage;
    case: "metaMessage";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message core.v1.messages.UserMessage.
 * Use `create(UserMessageSchema)` to create a new message.
 */
export const UserMessageSchema: GenMessage<UserMessage> = /*@__PURE__*/
  messageDesc(file_v1_messages_user_messages, 0);

/**
 * @generated from message core.v1.messages.MetaGuess
 */
export type MetaGuess = Message<"core.v1.messages.MetaGuess"> & {
  /**
   * @generated from field: bool is_correct = 1;
   */
  isCorrect: boolean;

  /**
   * @generated from field: string country_id = 2;
   */
  countryId: string;
};

/**
 * Describes the message core.v1.messages.MetaGuess.
 * Use `create(MetaGuessSchema)` to create a new message.
 */
export const MetaGuessSchema: GenMessage<MetaGuess> = /*@__PURE__*/
  messageDesc(file_v1_messages_user_messages, 1);

/**
 * @generated from message core.v1.messages.MetaMessage
 */
export type MetaMessage = Message<"core.v1.messages.MetaMessage"> & {
};

/**
 * Describes the message core.v1.messages.MetaMessage.
 * Use `create(MetaMessageSchema)` to create a new message.
 */
export const MetaMessageSchema: GenMessage<MetaMessage> = /*@__PURE__*/
  messageDesc(file_v1_messages_user_messages, 2);

